# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccfdf2e04369a902107a02fa0614ad0804d619a802eb0ad81f456afeef83721704d021b682d6fd1c9aef59de2bb1d504727206be29da2c838024a574f99dfdae

test:
  secret_key_base: cdde3d00ca44c3bdcee0fdfff14fee40cf9b9a79cbfac18a4fcae71124d2cfdf60c2381ec1927458e32b0c114627087d1a7b59eee3fc9867947321655dee9519

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
